version: '3.8'

# volumes:
#   mongo_data:
#   redis_data:

services:
    mongo:
        image: mongo
        restart: always
        # ports:
        #  - "27017:27017"
        command: --wiredTigerCacheSizeGB .5
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            # MONGO_INITDB_DATABASE: darksearch

    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #         - 8081:8081
    #     depends_on:
    #         - mongo
    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: example
    #         ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

    redis:
        image: 'redis:alpine'
        restart: always
        command: redis-server --save 60 10 --loglevel warning --maxmemory-policy noeviction
        # ports:
        #  - "6379:6379"
        # volumes:
        #   - redis_data:/data
        deploy:
            resources:
                limits:
                    # cpus: '0.50'
                    memory: 1G

    # redisinsight:
    #     image: redislabs/redisinsight:latest
    #     ports:
    #         - '8002:8001'

    tor:
        build:
            context: ./docker/tor
            dockerfile: Dockerfile
        # ports:
        #     - 9050:9050

    crawler:
        build:
            context: .
            dockerfile: crawler/Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - redis
            - mongo
            - tor
        environment:
            - SENTRY_DSN=${SENTRY_DSN}
            - NODE_ENV=production
            # - NODE_ENV=dev
