version: '3.8'

services:
    db:
        image: postgres:14-alpine
        # restart: always
        environment:
            POSTGRES_PASSWORD: example

    redis:
        image: 'redis:alpine'
        # restart: always
        command: redis-server --save 60 10 --loglevel warning --maxmemory-policy noeviction
        # ports:
        #  - "6379:6379"
        # volumes:
        #   - redis_data:/data
        deploy:
            resources:
                limits:
                    # cpus: '0.50'
                    memory: 1G

    # redisinsight:
    #     image: redislabs/redisinsight:latest
    #     ports:
    #         - '8002:8001'

    tor:
        build:
            context: ./docker/tor
            dockerfile: Dockerfile
        # ports:
        #     - 9050:9050

    crawler:
        build:
            context: .
            dockerfile: crawler/Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - redis
            - db
            - tor
        environment:
            - SENTRY_DSN=${SENTRY_DSN}
            - NODE_ENV=production
            - DATABASE_URL=${DATABASE_URL}
            # - NODE_ENV=dev
